name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet
        run: pip install flet

      - name: Build APK
        uses: flet-dev/build-apk-action@v1
        with:
          path: main.py
          requirements: flet
          app_name: Calculadora
          app_org: com.marvel

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Calculadora
          path: output/apk/*.apk
